name: Setup Kubernetes context
description: Writes kubeconfig, fixes permissions, chooses context, exports KUBECONFIG.

inputs:
  kubeconfig_data:
    required: true
  context_name:
    required: false
    default: ""

outputs:
  kubeconfig_path:
    value: ${{ steps.setup.outputs.kubeconfig_path }}
  selected_context:
    value: ${{ steps.setup.outputs.selected_context }}

runs:
  using: composite
  steps:
    - id: setup
      shell: bash
      run: |
        # Write kubeconfig (handles base64 or plain)
        echo "${{ inputs.kubeconfig_data }}" | base64 -d > kubeconfig.yaml 2>/dev/null || echo "${{ inputs.kubeconfig_data }}" > kubeconfig.yaml

        chmod 600 kubeconfig.yaml

        export KUBECONFIG="$(pwd)/kubeconfig.yaml"

        echo "KUBECONFIG=$KUBECONFIG" >> "$GITHUB_ENV"
        echo "kubeconfig_path=$KUBECONFIG" >> "$GITHUB_OUTPUT"

        # If context_name is supplied, try to use that explicitly
        if [[ -n "${{ inputs.context_name }}" ]]; then
          ctx="${{ inputs.context_name }}"
          # Verify it actually exists
          if ! kubectl config get-contexts -o name | grep -Fxq "$ctx"; then
            echo "❌ Specified context '${{ inputs.context_name }}' not found in kubeconfig"
            echo "Available contexts:"
            kubectl config get-contexts || true
            exit 1
          fi
        else
          # Grab the first real context
          ctx=$(kubectl config get-contexts -o name | head -n 1)
        fi

        if [[ -z "$ctx" ]]; then
          echo "❌ No contexts found in kubeconfig"
          kubectl config get-contexts || true
          exit 1
        fi

        echo "Using Kubernetes context: $ctx"
        kubectl config use-context "$ctx"

        echo "selected_context=$ctx" >> "$GITHUB_OUTPUT"

        # Sanity check (non-fatal)
        kubectl cluster-info || echo "⚠️ Warning: cluster unreachable (but continuing)"
