name: Prepare matrix JSON for modules/environments
description: Builds modules_json and matrix_json for matrix strategy

inputs:
  modules:
    description: "Comma-separated list of modules (e.g. 'api,worker,backend')"
    required: true
    default: "api"
  environments:
    description: "Comma-separated list of environments (e.g. 'prod,staging')"
    required: true
    default: "prod"
  release_overrides:
    description: |
      Optional per-module release name overrides in the form:
      "api:googlecalendartoluma-api,worker:googlecalendartoluma-worker".
      For a given module, if an override exists, it is used.
      If no override exists, releaseName defaults to the module name.
    required: false
    default: ""

outputs:
  modules_json:
    description: "Matrix JSON for modules only"
    value: ${{ steps.modules.outputs.modules_json }}
  matrix_json:
    description: "Full matrix JSON for module+environment (+ releaseName)"
    value: ${{ steps.matrix.outputs.matrix_json }}

runs:
  using: composite
  steps:
    - id: modules
      name: Construct modules-only matrix JSON
      shell: bash
      run: |
        set -euo pipefail

        MODULES_JSON='{"include":['
        IFS=',' read -ra MODULES <<< "${{ inputs.modules }}"
        for module in "${MODULES[@]}"; do
          [[ -z "$module" ]] && continue
          module_lower=$(echo "$module" | tr '[:upper:]' '[:lower:]')
          MODULES_JSON+='{"module":"'"$module"'","module_lower":"'"$module_lower"'"},'
        done
        MODULES_JSON=${MODULES_JSON%,}
        MODULES_JSON+=']}'

        echo "Modules JSON: $MODULES_JSON"
        echo "modules_json=$MODULES_JSON" >> "$GITHUB_OUTPUT"

    - id: matrix
      name: Construct full matrix JSON
      shell: bash
      run: |
        set -euo pipefail

        MODULES_STR="${{ inputs.modules }}"
        ENVS_STR="${{ inputs.environments }}"
        RELEASE_OVERRIDES_STR="${{ inputs.release_overrides }}"

        # Parse per-module release overrides. module_name:release_name
        declare -A RELEASE_MAP
        if [[ -n "$RELEASE_OVERRIDES_STR" ]]; then
          IFS=',' read -ra PAIRS <<< "$RELEASE_OVERRIDES_STR"
          for pair in "${PAIRS[@]}"; do
            [[ -z "$pair" ]] && continue
            key="${pair%%:*}"
            val="${pair#*:}"
            [[ -z "$key" || -z "$val" ]] && continue
            RELEASE_MAP["$key"]="$val"
          done
        fi

        IFS=',' read -ra MODULES <<< "$MODULES_STR"
        IFS=',' read -ra ENVIRONMENTS <<< "$ENVS_STR"

        MATRIX_JSON='{"include":['

        for env in "${ENVIRONMENTS[@]}"; do
          for module in "${MODULES[@]}"; do
            [[ -z "$module" ]] && continue

            module_lower=$(echo "$module" | tr '[:upper:]' '[:lower:]')

            # Per-module override > default (module name)
            if [[ -n "${RELEASE_MAP[$module]+x}" ]]; then
              releaseName="${RELEASE_MAP[$module]}"
            else
              releaseName="$module"
            fi

            MATRIX_JSON+="{\"environment\":\"$env\",\"module\":\"$module\",\"module_lower\":\"$module_lower\",\"releaseName\":\"$releaseName\"},"
          done
        done

        MATRIX_JSON="${MATRIX_JSON%,}]}"
        echo "MATRIX_JSON=$MATRIX_JSON"
        echo "matrix_json=$MATRIX_JSON" >> "$GITHUB_OUTPUT"
